In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
credit_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IIT HACKATHON/Dev_data_to_be_shared.csv")

In [4]:
credit_data.head()

,account_number,bad_flag,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,...,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50,onus_attribute_43,onus_attribute_44,onus_attribute_45,onus_attribute_46,onus_attribute_47,onus_attribute_48
0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2,0,221000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0,25000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN
3,4,0,86000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN
4,5,0,215000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# On-us attributes: Related to the customerâ€™s credit limit or the credit utilization
# Transaction attributes: Represent customer transaction patterns (e.g., number of transactions, transaction value across merchant types).
# Bureau tradeline attributes: Historical delinquency and product holding details.
# Bureau inquiry attributes: Represent recent credit inquiries reported by credit bureaus (e.g., number of personal loan inquiries in the past 3 months).

In [6]:
credit_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96806 entries, 0 to 96805
Columns: 1216 entries, account_number to onus_attribute_48
dtypes: float64(1189), int64(27)
memory usage: 898.1 MB

In [7]:
credit_data.describe()

,account_number,bad_flag,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,...,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50,onus_attribute_43,onus_attribute_44,onus_attribute_45,onus_attribute_46,onus_attribute_47,onus_attribute_48
count,96806.000000,96806.000000,7.157500e+04,71575.000000,71575.000000,71575.000000,71575.000000,71575.000000,71575.000000,71575.000000,...,94212.0,94212.000000,94212.000000,94212.000000,11610.000000,11610.000000,11610.000000,11610.000000,11610.000000,11610.000000
mean,48403.500000,0.014173,1.542391e+05,9.570769,0.002207,4.092854,77.306435,0.006315,67.043550,0.081034,...,0.0,0.189657,0.044283,7.800673,0.588114,1.497158,0.545650,1.430491,0.121447,0.119208
std,27945.629417,0.118203,1.729925e+05,1513.967595,0.119240,301.580599,3164.987013,0.129545,2516.330899,14.203615,...,0.0,0.597298,0.369451,8.655149,1.059613,1.702795,1.055865,1.728950,0.601256,0.599697
min,1.000000,0.000000,2.500000e+04,0.000000,0.000000,0.000000,-109800.476600,0.000000,-3498.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,24202.250000,0.000000,5.900000e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,2.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
50%,48403.500000,0.000000,1.000000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,5.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
75%,72604.750000,0.000000,1.810000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,11.000000,1.000000,2.000000,1.000000,2.000000,0.000000,0.000000
max,96806.000000,1.000000,2.800000e+06,398936.791000,25.000000,55000.000000,358986.000000,12.000000,358986.000000,3150.000000,...,0.0,18.000000,14.000000,102.000000,19.000000,38.000000,19.000000,38.000000,15.000000,15.000000

In [8]:
credit_data.isnull().sum()

account_number                 0
bad_flag                       0
onus_attribute_1           25231
transaction_attribute_1    25231
transaction_attribute_2    25231
                           ...
onus_attribute_44          85196
onus_attribute_45          85196
onus_attribute_46          85196
onus_attribute_47          85196
onus_attribute_48          85196
Length: 1216, dtype: int64

In [9]:
bureau_enquiry_columns = []
for col in credit_data.columns:
    if col.startswith("bureau_enquiry"):
        bureau_enquiry_columns.append(col)

for col in credit_data.columns:
    if col not in bureau_enquiry_columns:
      credit_data[col].fillna(credit_data[col].mean(), inplace=True)

for col in bureau_enquiry_columns:
    credit_data[col].fillna(0, inplace=True)

<ipython-input-9-2ee0b420ca26>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_data[col].fillna(credit_data[col].mean(), inplace=True)
<ipython-input-9-2ee0b420ca26>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_data[col].fillna(0, inplace=True)

In [10]:
credit_data.isnull().sum()

account_number             0
bad_flag                   0
onus_attribute_1           0
transaction_attribute_1    0
transaction_attribute_2    0
                          ..
onus_attribute_44          0
onus_attribute_45          0
onus_attribute_46          0
onus_attribute_47          0
onus_attribute_48          0
Length: 1216, dtype: int64

In [11]:
null_counts = credit_data.isnull().sum()
print("Null values in each column:")
print(null_counts[null_counts > 0])

Null values in each column:
bureau_436    96806
bureau_447    96806
dtype: int64

In [12]:
# these columns are fully NULL so we replace them with 0
credit_data['bureau_436'].fillna(0, inplace=True)
credit_data['bureau_447'].fillna(0, inplace=True)

<ipython-input-12-db27ff18d34f>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_data['bureau_436'].fillna(0, inplace=True)
<ipython-input-12-db27ff18d34f>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  credit_data['bureau_447'].fillna(0, inplace=True)

In [13]:
null_counts = credit_data.isnull().sum()
print("Null values in each column:")
print(null_counts[null_counts > 0])

Null values in each column:
Series([], dtype: int64)

In [14]:
credit_data.head()

,account_number,bad_flag,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,...,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50,onus_attribute_43,onus_attribute_44,onus_attribute_45,onus_attribute_46,onus_attribute_47,onus_attribute_48
0,1,0,154239.119804,9.570769,0.002207,4.092854,77.306435,0.006315,67.04355,0.081034,...,0.0,0.0,0.0,1.0,0.588114,1.497158,0.54565,1.430491,0.121447,0.119208
1,2,0,221000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.0,0.0,2.0,3.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
2,3,0,25000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.0,0.0,0.0,8.0,0.588114,1.497158,0.54565,1.430491,0.121447,0.119208
3,4,0,86000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.0,0.0,0.0,30.0,0.588114,1.497158,0.54565,1.430491,0.121447,0.119208
4,5,0,215000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.0,0.0,0.0,1.0,0.588114,1.497158,0.54565,1.430491,0.121447,0.119208

In [15]:
credit_data['bad_flag'].value_counts()

bad_flag
0    95434
1     1372
Name: count, dtype: int64

In [16]:
X = credit_data.drop(columns=["bad_flag", "account_number"])  # Drop target and primary key
y = credit_data["bad_flag"]

In [17]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [18]:
X_scaled

array([[-1.95657482e-16,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  6.68255084e-17],
       [ 4.48816033e-01, -7.35197037e-03, -2.15301666e-02, ...,
        -2.38922175e+00, -5.83285231e-01, -5.74018513e-01],
       [-8.68840987e-01, -7.35197037e-03, -2.15301666e-02, ...,
         0.00000000e+00,  0.00000000e+00,  6.68255084e-17],
       ...,
       [-3.98249194e-01, -7.35197037e-03, -2.15301666e-02, ...,
         0.00000000e+00,  0.00000000e+00,  6.68255084e-17],
       [-4.45308374e-01, -7.35197037e-03, -2.15301666e-02, ...,
         0.00000000e+00,  0.00000000e+00,  6.68255084e-17],
       [-4.04971934e-01, -7.35197037e-03, -2.15301666e-02, ...,
         0.00000000e+00,  0.00000000e+00,  6.68255084e-17]])

In [19]:
# Splitting data into training and validation
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [20]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(77444, 1214) (19362, 1214) (77444,) (19362,)

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
models = [LogisticRegression(), DecisionTreeClassifier(), RandomForestClassifier(), GradientBoostingClassifier(), KNeighborsClassifier(), XGBClassifier()]

/usr/local/lib/python3.10/dist-packages/dask/dataframe/__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

In [22]:
import sklearn.metrics as mt
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

In [23]:
best_score = 0
best_model = None
for model in models:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    score = model.score(X_test, y_test)
    print(f"{model.__class__.__name__}:")
    print("Accuracy:", mt.accuracy_score(y_test, y_pred))
    print("Precision:", mt.precision_score(y_test, y_pred, average='weighted'))
    print("Recall:", mt.recall_score(y_test, y_pred, average='weighted'))
    print("F1-score:", mt.f1_score(y_test, y_pred, average='weighted'))
    print("Score:", score)
    print()
    if score > best_score:
        best_score = score
        best_model = model
    print("Best model updated:", best_model)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression:
Accuracy: 0.9849189133353993
Precision: 0.9753478160715846
Recall: 0.9849189133353993
F1-score: 0.9791985441499252
Score: 0.9849189133353993

Best model updated: LogisticRegression()
DecisionTreeClassifier:
Accuracy: 0.9692697035430224
Precision: 0.9732416590417854
Recall: 0.9692697035430224
F1-score: 0.9712411898207213
Score: 0.9692697035430224

Best model updated: LogisticRegression()
RandomForestClassifier:
Accuracy: 0.9860551595909514
Precision: 0.9723047777559365
Recall: 0.9860551595909514
F1-score: 0.9791316953716358
Score: 0.9860551595909514

Best model updated: RandomForestClassifier()

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

GradientBoostingClassifier:
Accuracy: 0.9846090279929759
Precision: 0.9736640672523624
Recall: 0.9846090279929759
F1-score: 0.9786821712550919
Score: 0.9846090279929759

Best model updated: RandomForestClassifier()
KNeighborsClassifier:
Accuracy: 0.9854870364631753
Precision: 0.9734191808839823
Recall: 0.9854870364631753
F1-score: 0.9789457416489385
Score: 0.9854870364631753

Best model updated: RandomForestClassifier()
XGBClassifier:
Accuracy: 0.9856419791343869
Precision: 0.9737431100472156
Recall: 0.9856419791343869
F1-score: 0.9790243074114185
Score: 0.9856419791343869

Best model updated: RandomForestClassifier()

In [24]:
print("Best Model:", best_model.__class__.__name__, ", Best Score:", best_score)

Best Model: RandomForestClassifier , Best Score: 0.9860551595909514

In [25]:
validation_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IIT HACKATHON/validation_data_to_be_shared.csv")  # Replace with your actual dataset

In [26]:
validation_data.head()

,account_number,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,transaction_attribute_8,...,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50,onus_attribute_43,onus_attribute_44,onus_attribute_45,onus_attribute_46,onus_attribute_47,onus_attribute_48
0,100001,34000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,32.0,NaN,NaN,NaN,NaN,NaN,NaN
1,100002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,100003,130000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN
3,100004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,100005,53000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
bureau_enquiry_columns = []
for col in validation_data.columns:
    if col.startswith("bureau_enquiry"):
        bureau_enquiry_columns.append(col)

for col in validation_data.columns:
    if col not in bureau_enquiry_columns:
      validation_data[col].fillna(validation_data[col].mean(), inplace=True)

for col in bureau_enquiry_columns:
    validation_data[col].fillna(0, inplace=True)

<ipython-input-27-f0912a44590c>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  validation_data[col].fillna(validation_data[col].mean(), inplace=True)
<ipython-input-27-f0912a44590c>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  validation_data[col].fillna(0, inplace=True)

In [28]:
validation_data.isnull().sum()

account_number             0
onus_attribute_1           0
transaction_attribute_1    0
transaction_attribute_2    0
transaction_attribute_3    0
                          ..
onus_attribute_44          0
onus_attribute_45          0
onus_attribute_46          0
onus_attribute_47          0
onus_attribute_48          0
Length: 1215, dtype: int64

In [29]:
null_counts = validation_data.isnull().sum()
print("Null values in each column:")
print(null_counts[null_counts > 0])

Null values in each column:
bureau_436    41792
bureau_447    41792
dtype: int64

In [30]:
validation_data['bureau_436'].fillna(0, inplace=True)
validation_data['bureau_447'].fillna(0, inplace=True)

<ipython-input-30-c80bc4a83ab7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  validation_data['bureau_436'].fillna(0, inplace=True)
<ipython-input-30-c80bc4a83ab7>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  validation_data['bureau_447'].fillna(0, inplace=True)

In [31]:
null_counts = validation_data.isnull().sum()
print("Null values in each column:")
print(null_counts[null_counts > 0])

Null values in each column:
Series([], dtype: int64)

In [32]:
validation_data.head()

,account_number,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,transaction_attribute_8,...,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50,onus_attribute_43,onus_attribute_44,onus_attribute_45,onus_attribute_46,onus_attribute_47,onus_attribute_48
0,100001,34000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,32.0,0.550869,1.446132,0.504697,1.377174,0.111133,0.108735
1,100002,153535.906759,4.934193,0.001851,4.402052,80.126844,0.006818,68.482478,0.014609,0.000065,...,0.0,0.0,0.0,0.0,0.550869,1.446132,0.504697,1.377174,0.111133,0.108735
2,100003,130000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,2.0,0.0,12.0,0.550869,1.446132,0.504697,1.377174,0.111133,0.108735
3,100004,153535.906759,4.934193,0.001851,4.402052,80.126844,0.006818,68.482478,0.014609,0.000065,...,0.0,0.0,0.0,1.0,0.550869,1.446132,0.504697,1.377174,0.111133,0.108735
4,100005,53000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,18.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [33]:
# Preprocess the validation data (similar to training data)
validation_scaled = scaler.transform(validation_data.drop(columns=["account_number"]))

In [34]:
validation_scaled

array([[-0.80833633, -0.00735197, -0.02153017, ..., -0.08905108,
        -0.04953463, -0.05042962],
       [-0.00472752, -0.00356168, -0.0034814 , ..., -0.08905108,
        -0.04953463, -0.05042962],
       [-0.1629533 , -0.00735197, -0.02153017, ..., -0.08905108,
        -0.04953463, -0.05042962],
       ...,
       [ 0.0051152 , -0.00735197, -0.02153017, ..., -0.08905108,
        -0.04953463, -0.05042962],
       [-0.37135823, -0.00735197, -0.02153017, ..., -0.08905108,
        -0.04953463, -0.05042962],
       [-0.15623056, -0.00735197, -0.02153017, ..., -0.08905108,
        -0.04953463, -0.05042962]])

In [35]:
# Predict probabilities
validation_data["default_probability"] = best_model.predict(validation_scaled)

In [36]:
validation_data[["account_number", "default_probability"]].to_csv("predictions2.csv", index=False)

In [37]:
validation_data['default_probability'].value_counts()

default_probability
0    41474
1      318
Name: count, dtype: int64